server:
  port:
    8081

spring:
  application:
    name: fraud
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=fraud
    username: postgres
    password: postgres